name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Meson and Ninja
        run: pip install meson ninja
      
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      
      - name: Configure
        run: meson setup builddir --prefix=${{ github.workspace }}/install -Ddefault_library=static
      
      - name: Build
        run: meson compile -C builddir
      
      - name: Install
        run: meson install -C builddir
      
      - name: Package
        run: |
          cd install
          7z a ../abx-tools-windows-${{ matrix.arch }}.zip *
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: abx-tools-windows-${{ matrix.arch }}
          path: abx-tools-windows-${{ matrix.arch }}.zip

  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            abi: arm64-v8a
            api: 29
            triplet: aarch64-linux-android
          - arch: armv7a
            abi: armeabi-v7a
            api: 29
            triplet: armv7a-linux-androideabi
          - arch: x86_64
            abi: x86_64
            api: 29
            triplet: x86_64-linux-android
          - arch: i686
            abi: x86
            api: 29
            triplet: i686-linux-android
          - arch: riscv64
            abi: riscv64
            api: 35
            triplet: riscv64-linux-android
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Meson and Ninja
        run: pip install meson ninja
      
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29
          add-to-path: false
      
      - name: Create Cross File
        run: |
          cat > android-${{ matrix.arch }}.txt << EOF
          [binaries]
          c = '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.triplet }}${{ matrix.api }}-clang'
          cpp = '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ matrix.triplet }}${{ matrix.api }}-clang++'
          ar = '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'
          strip = '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip'

          [properties]
          sys_root = '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/sysroot'
          c_args = ['-O3', '-DNDEBUG', '-flto=thin', '-ffast-math', '-fomit-frame-pointer', '-ffunction-sections', '-fdata-sections']
          cpp_args = ['-O3', '-DNDEBUG', '-flto=thin', '-ffast-math', '-fomit-frame-pointer', '-ffunction-sections', '-fdata-sections']
          c_link_args = ['-static', '-flto=thin', '-Wl,--gc-sections', '-Wl,--strip-all']
          cpp_link_args = ['-static', '-flto=thin', '-Wl,--gc-sections', '-Wl,--strip-all']

          [host_machine]
          system = 'android'
          cpu_family = '${{ matrix.arch == 'armv7a' && 'arm' || matrix.arch == 'i686' && 'x86' || matrix.arch }}'
          cpu = '${{ matrix.arch }}'
          endian = 'little'
          EOF
      
      - name: Configure
        run: |
          meson setup builddir \
            --cross-file android-${{ matrix.arch }}.txt \
            --prefix=${{ github.workspace }}/install \
            -Ddefault_library=static
      
      - name: Build
        run: meson compile -C builddir
      
      - name: Install
        run: meson install -C builddir
      
      - name: Strip binaries
        run: |
          ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip install/bin/*
      
      - name: Package
        run: |
          cd install
          tar -czf ../abx-tools-android-${{ matrix.arch }}.tar.gz *
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: abx-tools-android-${{ matrix.arch }}
          path: abx-tools-android-${{ matrix.arch }}.tar.gz

  release:
    needs: [build-windows, build-android]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate tag name
        id: tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            COMMIT_MSG=$(git log -1 --pretty=%s)
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            TAG_NAME="v${TIMESTAMP}-${COMMIT_MSG//[^a-zA-Z0-9]/-}"
            TAG_NAME=$(echo "$TAG_NAME" | tr '[:upper:]' '[:lower:]' | cut -c1-50)
            echo "name=$TAG_NAME" >> $GITHUB_OUTPUT
          fi
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.name }}
          name: Release ${{ steps.tag.outputs.name }}
          body: |
            Automated release for commit: ${{ github.sha }}
            Commit message: ${{ github.event.head_commit.message }}
          files: |
            artifacts/abx-tools-windows-x64/*.zip
            artifacts/abx-tools-windows-x86/*.zip
            artifacts/abx-tools-android-aarch64/*.tar.gz
            artifacts/abx-tools-android-armv7a/*.tar.gz
            artifacts/abx-tools-android-x86_64/*.tar.gz
            artifacts/abx-tools-android-i686/*.tar.gz
            artifacts/abx-tools-android-riscv64/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
